//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Logs = new HashSet<Log>();
        }
    
        public string Username { get; set; }
        public int Employee_ID { get; set; }
        public string Email { get; set; }
        public string Full_Name { get; set; }
        public string Password { get; set; }
        public System.DateTime Join_Date { get; set; }
        public int Position { get; set; }
        public int Team { get; set; }
        public string Security_Phrase { get; set; }
        public int Status { get; set; }
        public int Login_Attempts { get; set; }
    
        public virtual Position Position1 { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Team Team1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Logs { get; set; }
    }
}
